### ISSUE TITLE
Implement hook_config_info()

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/rrssb#6]
Whenever I try to synchronize the config I always get an error with this module.

> Configuration sync failed. The following errors were reported:
> The configuration "rrssb.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

But it is enabled.

**Comment by indigoxela** [comment]
@laryn you forgot to implement [hook_config_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_info/1)

At least I didn't find it in rrssb.module.

**Comment by laryn** [comment]
Good catch, @keiserjb can you test https://github.com/backdrop-contrib/rrssb/commit/712a3c1c25f4ad1009ece0b9321449a6695ba69d ?

Thanks to you both.

**Comment by keiserjb** [comment]
That works much better.  Thank you.
